# Site settings
title: Sagar Pathrudkar
email: 
description: "random"
baseurl: ""
url: "http://sagarpath.github.io"
twitter_username: sagarpath
github_username:  sagarpath

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
